# Generated by Django 3.0.2 on 2020-02-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joke',
            old_name='text',
            new_name='body',
        ),
        migrations.AddField(
            model_name='joke',
            name='punchline',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
