# Generated by Django 3.0.2 on 2020-02-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20200207_2338'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jokefavorite',
            constraint=models.UniqueConstraint(fields=('joke', 'user'), name='unique_jokes_favorite'),
        ),
    ]
